### ISSUE TITLE
Create crawler for Bell county 

### ISSUE THREAD

**Issue by jameskip** [jameskip/texas-vaccines#1]
### Frontends:
Killeen:
https://outlook.office365.com/owa/calendar/BellCountyTechnologyServices1@bellcountytx.onmicrosoft.com/bookings/

Temple: https://outlook.office365.com/owa/calendar/BellCountyTechnologyServices2@bellcountytx.onmicrosoft.com/bookings/

### Endpoints:
Killeen: `https://outlook.office365.com/owa/calendar/BellCountyTechnologyServices1@bellcountytx.onmicrosoft.com/bookings/service.svc/GetStaffBookability`

Tample: `https://outlook.office365.com/owa/calendar/BellCountyTechnologyServices2@bellcountytx.onmicrosoft.com/bookings/service.svc/GetStaffBookability`

### Response:
![Screen Shot 2021-02-01 at 12 29 29 PM](https://user-images.githubusercontent.com/16872140/106501830-35275780-6489-11eb-8923-ecc2a26dda5e.png)

### Example Request Options
```json
{
    "method": "POST",
    "hostname": "outlook.office365.com",
    "path": "/owa/calendar/BellCountyTechnologyServices1@bellcountytx.onmicrosoft.com/bookings/service.svc/GetStaffBookability",
    "headers": {
      "Connection": " keep-alive",
      "Content-Length": " 167",
      "User-Agent": " Mozilla/5.0 (Macintosh; Intel Mac OS X 11_1_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.96 Safari/537.36",
      "DNT": " 1",
      "Content-Type": " application/json; charset=UTF-8",
      "Accept": " */*",
      "Origin": " https://outlook.office365.com",
      "Sec-Fetch-Site": " same-origin",
      "Sec-Fetch-Mode": " cors",
      "Sec-Fetch-Dest": " empty",
      "Accept-Encoding": " gzip, deflate, br",
      "Accept-Language": " en-US,en;q=0.9",
      "Cookie": " ClientId=BE2D9ACA38F24040B4F9F9A3A37B3159; OIDC=1; OutlookSession=cf26724c32b8467e8997c525221825ff; ClientId=464769C1B88C47E0A6E746414E366D2D; OIDC=1; OutlookSession=72b8901a81104458bc18057328ef9d0d"
    },
    "maxRedirects": 20
  }
```

**Comment by jameskip** [comment]
I'm having trouble determining which status code in `BookableDays` from the request indicates that there are open timeslots.
I know it is not `1` or `2` but since this request does not have any `BookableDays` I don't know what number it could be.
```json
{            
  "BookableDays": [
    {
        "Date": "2021-01-31T00:00:00-06:00",
        "Status": 2
    },
    {
        "Date": "2021-02-01T00:00:00-06:00",
        "Status": 1
    },
    {
        "Date": "2021-02-02T00:00:00-06:00",
        "Status": 1
    },
    {
        "Date": "2021-02-03T00:00:00-06:00",
        "Status": 1
    },
  ]
}

**Comment by AshtonTX** [comment]
Using the endpoint for Bell County's 2nd dose:

`https://outlook.office365.com/owa/calendar/BeltonBellCountyTexas@bellcountytx.onmicrosoft.com/bookings/service.svc/GetStaffBookability` 

Dates that are available and unavailable in `BookableDays` are also returning a status of `1`. I'm thinking it may be best to use `BookableItems` rather than `BookableDays`.

**Comment by jameskip** [comment]
![Screen Shot 2021-02-01 at 3 58 36 PM](https://user-images.githubusercontent.com/16872140/106690936-41e6a100-6598-11eb-9ad6-a6e4f4662bb8.png)
