### ISSUE TITLE
Create checker for FHS

### ISSUE THREAD

**Issue by deloreyj** [jameskip/texas-vaccines#3]
https://intakeq.com/booking/qfrufw

**Comment by jameskip** [comment]
Looks like user @dougmc beat us to it. See room `#aph-updates`

**Comment by jameskip** [comment]
Returns a list of `services` starting around 38 are the covid vaccine services. In there there are `location` properties that hold the ids to the location with that service. Not sure where to find the indicator for vaccines.

![Screen Shot 2021-02-03 at 3 39 30 PM](https://user-images.githubusercontent.com/16872140/106812974-08fd0980-6636-11eb-9b35-9b08a389200d.png)

**Comment by jameskip** [comment]
Done.
